# If Stack has difference, notify to slack

name: Check Stack Difference

on:
  pull_request:
    branches: [ "*" ]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: cdk bootstrap
        id: bootstrap
        uses: arnaskro/aws-cdk-v2-github-actions@v2.3.0
        with:
          cdk_subcommand: 'bootstrap'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      - name: cdk diff
        id: diff
        uses: arnaskro/aws-cdk-v2-github-actions@v2.3.0
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

      # https://github.com/marketplace/actions/action-slack
      - name: notify slack
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: GitHubActions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: steps.diff.outputs.status_code == 1
